# Tomcat
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.138.130:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
  redis:
    host: 192.168.138.130
    port: 6379
  rabbitmq:
    host: 192.168.138.130
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
  session:
    store-type: redis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
myRabbitmq:
  queue: mall-queue
  exchange: mall-exchange
  routeKey: mall
  MQConfig:
    # 订单队列
    queues: order.release.order.queue
    delayQueue: order.delay.queue
    seckillQueue: order.seckill.order.queue
    eventExchange: order-event-exchange
    routingKey: order.release.order
    seckillOrderKey: order.seckill.order
    createOrder: order.create.order
    # 订单自动过期时间 单位:(毫秒)
    ttl: 900000
    # 库存解锁队列
    ReleaseOther: stock.release.stock.queue
    ReleaseOtherKey: order.release.other

server:
  port: 12000

gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10